<?php
/**
 * @category EasyNolo
 * @package  EasyNolo_BancaSellaPro
 * @author   Easy Nolo <ecommerce@sella.it>
 */
?>

<?php /* @var $this EasyNolo_BancaSellaPro_Block_Form */?>
<?php /* @var $method EasyNolo_BancaSellaPro_Model_Gestpay */?>
<?php $method = $this->getMethod() ?>
<?php $_code=$this->getMethodCode() ?>
<?php $merchantId = $method->getMerchantId() ?>

<?php
try{
    /** @var EasyNolo_BancaSellaPro_Helper_Crypt $helper */
    $encriptString = false;

    if( $this->isIframeEnable() ){
        $helper =Mage::helper('easynolo_bancasellapro/crypt');
        $encriptString = $helper->getEncryptStringBeforeOrder($method);
    }
    ?>

    <fieldset class="form-list">
        <?php $_code=$this->getMethodCode() ?>
        <ul class="form-list" id="payment_iframe_<?php echo $_code ?>" style="display:none;">
            <li>
                <label for="<?php echo $_code ?>_cc_number" class="required"><em>*</em><?php echo $this->__('Credit Card Number') ?></label>
                <div class="input-box">
                    <input type="text" id="hid_<?php echo $_code ?>_cc_number" name="bancasella_iframe[cc_number]" title="<?php echo $this->__('Credit Card Number') ?>" class="input-text required-entry validate-number validate-cc-number" value="" autocomplete="off" />
                </div>
            </li>
            <li>
                <label for="hid_<?php echo $_code ?>_cc_exp_mm" class="required"><em>*</em><?php echo $this->__('Expiration Date') ?></label>
                <div class="input-box">
                    <div class="v-fix">
                        <select id="hid_<?php echo $_code ?>_cc_exp_mm" name="bancasella_iframe[cc_exp_mm]" class="month required-entry">
                            <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                                <option value="<?php echo $k?$k:'' ?>"><?php echo $v ?></option>
                            <?php endforeach ?>
                        </select>
                    </div>
                    <div class="v-fix">
                        <select id="hid_<?php echo $_code ?>_cc_exp_yy" name="bancasella_iframe[cc_exp_yy]" class="year required-entry">
                            <?php foreach ($this->getCcYears() as $k=>$v): ?>
                                <option value="<?php echo $k?$k:'' ?>"><?php echo $v ?></option>
                            <?php endforeach ?>
                        </select>
                    </div>
                </div>
            </li>
            <li>
                <label for="<?php echo $_code ?>_cc_cvv" class="required"><em>*</em><?php echo $this->__('CVV2 / 4DBC') ?></label>
                <div class="input-box">
                    <input type="text" id="hid_<?php echo $_code ?>_cc_cvv" name="bancasella_iframe[cc_cvv]" title="<?php echo $this->__('CVV2 / 4DBC') ?>" class="input-text required-entry validate-number" value="" autocomplete="off" />
                </div>
            </li>
            <li>
                <label for="<?php echo $_code ?>_cc_name" class="required"><em>*</em><?php echo $this->__('Name on Card') ?></label>
                <div class="input-box">
                    <input type="text" id="hid_<?php echo $_code ?>_cc_name" name="bancasella_iframe[cc_name]" title="<?php echo $this->__('Name on Card') ?>" class="input-text required-entry" value="" autocomplete="off" />
                </div>
            </li>
            <li>
                <label for="<?php echo $_code ?>_cc_email" class="required"><em>*</em><?php echo $this->__('Email') ?></label>
                <div class="input-box">
                    <input type="text" id="hid_<?php echo $_code ?>_cc_email" name="bancasella_iframe[cc_email]" title="<?php echo $this->__('Email') ?>" class="input-text required-entry validate-email" value="" autocomplete="off" />
                </div>
            </li>

        </ul>

        <ul id="payment_form_<?php echo $_code ?>" style="display: none;">
            <li>
                <?php  echo $this->__($method->getConfigData ( 'description' )) ?>
            </li>
        </ul>
        <?php if($encriptString): ?>
        <script type="text/javascript">
            //<![CDATA[
            if ( typeof BancaSellaForm !== 'undefined'){

                var GestPayConfig = {};
                GestPayConfig.merchantId = '<?php echo $merchantId ?>';
                GestPayConfig.stringEnctipt = '<?php echo $encriptString ?>';
                GestPayConfig.formId = 'payment_iframe_<?php echo $_code ?>';
                GestPayConfig.radioBancaSella= 'p_method_<?php echo $_code ?>';
                GestPayConfig.cssSelectorInfo = '#payment_form_<?php echo $_code ?> li';
                GestPayConfig.GestPayExternalClass = GestPay;
                GestPayConfig.idStart = 'hid_<?php echo $_code ?>';
                GestPayConfig.cssSelectorRadioPayment = '#checkout-payment-method-load input[type="radio"]';
                GestPayConfig.confirmPage = '<?php echo $this->getPage3d(); ?>';
                GestPayConfig.authPage = '<?php echo $this->getAuthPage(); ?>';
                GestPayConfig.showHidePaymentDivId = 'opc-payment';
                GestPayConfig.waitImage= '<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>';
                GestPayConfig.successRedirect = '<?php echo $this->getSuccessRedirect()?>';
                GestPayConfig.isRecurringProfile= '<?php echo $this->isRecurringProfile()?>';
                GestPayConfig.code= '<?php echo $_code ?>';

                GestPayConfig.enableFormToIframe = typeof BrowserEnabled !== 'undefined'? BrowserEnabled : false;

                BancaSellaForm.init(GestPayConfig);
            }
            //]]>
        </script>
    <?php endif; ?>
    </fieldset>
<?php
}catch(Exception $e){
    //se il modulo non è configurato correttamente potrebbe
    $_helper= Mage::helper('easynolo_bancasellapro');
    $_helper->log($e->getMessage());
}
?>